theme = "fleet_dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
shell = [ "nu", "-c" ]
bufferline = "always"
text-width = 120
mouse = false
rulers = [ 80, 120 ]
default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render      = true
character   = "▏"
skip-levels = 1

[editor.statusline]
mode.select = "select"
mode.normal = "normal"
mode.insert = "insert"
center      = [ "version-control" ]

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection" ]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
C-d = "delete_selection"
d = "delete_selection_noyank"
C-c = "change_selection"
c = "change_selection_noyank"
A-p = [ "goto_line_start", "paste_before" ]
A-P = [ "goto_line_end", "paste_after" ]
"C-/" = "toggle_comments"
A-h = "goto_line_start"
A-l = "goto_line_end"
A-j = [ "extend_to_line_bounds",  "delete_selection", "paste_after", "goto_line_start" ]
A-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "goto_line_start" ]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
