theme = "nice"

[editor]
default-line-ending = "lf"
line-number = "relative"
cursorline  = true
color-modes = true
bufferline  = "multiple"
text-width  = 120
mouse       = false
rulers      = [ 72, 120 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render      = true
character   = "▏"
# skip-levels = 1

[editor.statusline]
mode.normal = "nor"
mode.insert = "ins"
mode.select = "sel"
center      = [ "version-control" ]

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "all"

[editor.whitespace.characters]
space = "·"

[keys.normal]
esc   = [ "collapse_selection", "keep_primary_selection" ]
tab   = "goto_next_buffer"
S-tab = "goto_previous_buffer"
A-d   = "delete_selection"
d     = "delete_selection_noyank"
A-c   = "change_selection"
c     = "change_selection_noyank"
A-j   = [ "extend_to_line_bounds",  "delete_selection", "paste_after" ]
A-k   = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[keys.insert]
up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"
