[language-server.superhtml] # This can be removed
command = "superhtml"
args = ["lsp"]

[language-server.emmet]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "c"
indent = { unit = "\t", tab-width = 4 }

[[language]]
name = "rust"
indent = { unit = "\t", tab-width = 4 }

[[language]]
name = "html"
indent = { unit = "\t", tab-width = 2 }
language-servers = [ "superhtml", "emmet" ]

[[language]]
name = "javascript"
indent = { unit = "\t", tab-width = 4 }
