# Derived from base16_theme (NNB <nnbnh@protonmail.com>)

"ui.menu" = { fg = "black", bg = "white" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.linenr" = { fg = "gray", bg = "black" }
"ui.popup" = { modifiers = ["reversed"] }
"ui.linenr.selected" = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"ui.text.inactive" = { fg = "gray" }
"comment" = { fg = "gray" }
"ui.statusline" = { fg = "black", bg = "white" }
"ui.statusline.inactive" = { fg = "gray", bg = "white" }
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"variable" = "red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "yellow"
"ui.cursor.match" = { fg = "yellow", modifiers = ["underlined"] }
"string"  = "green"
"variable.other.member" = "green"
"constant.character.escape" = "cyan"
"function" = "blue"
"constructor" = "blue"
"special" = "blue"
"keyword" = "magenta"
"label" = "magenta"
"namespace" = "magenta"
"ui.help" = { fg = "white", bg = "black" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "blue" }
"ui.virtual" = { fg = "gray", modifiers = ["italic"] }
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "black" }

"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "black" }
"info" = "blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"

[palette]
red           = "#f65b74" # oklch(68% 0.20 015)
light-red     = "#fc9099" # oklch(77% 0.13 015)
yellow        = "#ffb900" # oklch(83% 0.18 082)
light-yellow  = "#ffd077" # oklch(88% 0.12 082)
green         = "#16d584" # oklch(77% 0.18 157)
light-green   = "#45fca4" # oklch(88% 0.19 157)
cyan          = "#0dccda" # oklch(77% 0.13 204)
light-cyan    = "#2eebfb" # oklch(86% 0.14 204)
blue          = "#43b2f6" # oklch(75% 0.14 240)
light-blue    = "#6cc4ff" # oklch(79% 0.12 240)
magenta       = "#f674d0" # oklch(74% 0.20 340)
light-magenta = "#ff9fe1" # oklch(82% 0.14 340)
black         = "#181818" # oklch(21% 0.00 000)
gray          = "#636363" # oklch(50% 0.00 000)
light-gray    = "#d7d7d7" # oklch(88% 0.00 000)
white         = "#f8f8f8" # oklch(98% 0.00 000)
default       = "black"
