"ui.text" = "white"
"ui.background" = { bg = "black" }
"ui.menu" = { fg = "light-gray", bg = "black" }
"ui.menu.selected" = { fg = "green" }
"ui.linenr" = { fg = "light-gray", bg = "black", modifiers = [ "dim" ] }
"ui.linenr.selected" = { fg = "light-gray", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.window" = { bg = "black" }
"ui.selection" = { modifiers = [ "reversed" ] }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.cursor" = { modifiers = [ "reversed" ] }
"ui.cursor.primary" = { modifiers = [ "reversed" ] }
"ui.virtual.whitespace" = { fg = "gray", modifiers = [ "dim" ] }
"ui.virtual.wrap" = { fg = "gray", modifiers = [ "dim" ] }
"ui.virtual.jump-label" = { fg = "green", underline.style = "line" }
"ui.virtual.ruler" = { bg = "gray", fg = "black" }
"ui.virtual.indent-guide" = { fg = "gray", modifiers = [ "bold" ] }

"comment" = { fg = "gray", modifiers = [ "italic" ] }

"diff.plus" = "light-green"
"diff.delta" = "light-yellow"
"diff.minus" = "light-red"

"diagnostic.hint" = { underline.style = "line" }
"diagnostic.info" = { fg = "cyan", underline.style = "line" }
"diagnostic.warning" = { fg = "yellow", underline.style = "curl" }
"diagnostic.error" = { fg = "red", underline.style = "curl" }
"ui.gutter" = { bg = "black" }
"info" = "cyan"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "red"
